[build]
  publish = "public"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."cleanup"]
  schedule = "0 3 */2 * *"

[[headers]]
  for = "/widget.js"
  [headers.values]
    Cache-Control = "public, max-age=300"
